[server]

# Max size, in megabytes, for files uploaded with the file_uploader.
# Default: 200
maxUploadSize = 10

[theme]

primaryColor="#588e94"
backgroundColor="#191a1d"
secondaryBackgroundColor="#4c4c4c"
textColor="#f5f5f5"
font="sans serif"
