[server]

# Max size, in megabytes, for files uploaded with the file_uploader.
# Default: 200
maxUploadSize = 10

[theme]

primaryColor="#4169e1"
backgroundColor="#191a1d"
secondaryBackgroundColor="#242527"
textColor="#f5f5f5"
