[server]

# Max size, in megabytes, for files uploaded with the file_uploader.
# Default: 200
maxUploadSize = 10

[theme]

primaryColor="#ccd5ae"
backgroundColor="#fefae0"
secondaryBackgroundColor="#faedcd"
textColor="#262730"
font="sans serif"
