[server]

# Max size, in megabytes, for files uploaded with the file_uploader.
# Default: 200
maxUploadSize = 10

[theme]

primaryColor="#00FFC7"
backgroundColor="#E0EFFF"
secondaryBackgroundColor="#F2F6FF"
textColor="#222222"
font="sans serif"
