[server]

# Max size, in megabytes, for files uploaded with the file_uploader.
# Default: 200
maxUploadSize = 10

[theme]

primaryColor="#00fff0"
backgroundColor="#17171a"
secondaryBackgroundColor="#202023"
textColor="#ffffff"
font="sans serif"
