[server]

# Max size, in megabytes, for files uploaded with the file_uploader.
# Default: 200
maxUploadSize = 10

[theme]

primaryColor="#041746"
backgroundColor="#f0f0f0"
secondaryBackgroundColor="#f2f2f2"
textColor="#040b29"
font="sans serif"
