[server]

# Max size, in megabytes, for files uploaded with the file_uploader.
# Default: 200
maxUploadSize = 10

[theme]

primaryColor="#63e3ff"
backgroundColor="#f5f5f5"
secondaryBackgroundColor="#444444"
textColor="#ffffff"
font="sans serif"
